language: ruby
rvm:
  - 2.1

sudo: false
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

before_script:
  # Ensure we make ChefDK's Ruby the default
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - bundle install
matrix:
  fast_finish: true
